#!/usr/bin/env bash

source $(dirname $0)/helpers.sh
LOG=/tmp/log/$(basename $0).log
mkdir -p /tmp/log

(
    display Starting build at $(date)

    display Update system
    (
        yum -y update
    ) 2>&1 | indent

    display Install yum packages
    (
        xargs yum -y install < $(dirname $0)/packages.txt
    ) 2>&1 | indent

    display run custom install script
    (
        if [ -f /vagrant/scripts/custom.sh ]; then
          sh /vagrant/scripts/custom.sh
        else
          echo "No custom script found"
        fi
    ) 2>&1 | indent

    yum clean all

) 2>&1 | tee $LOG
